### ISSUE TITLE
Refactor Effort

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack-dev-server#1057]
This is an issue to track source refactoring. The goal is to create a friendlier codebase for contribution and update the codebase to use current code conventions and capabilities within Node ~~4.x~~ 6.x.

- [x] bin/webpack-dev-server (#1102)
- [x] use `chalk` and `log-symbols` for cli output (#1102)
- [x] **client** (#1137)
  - [x]  remove pug file and loader, replace with `script type="text/html"` template 
  - [x]  move client static files to `/public` on build
  - [x]  remove jquery dependency
  - [x]  refactor client scripts
  - [x]  Improve logging, use `loglevel`
- [x] **lib** (#1152)
  - [x] use `ws` for socket server
  - [x] use native `WebSocket` on the client
  - [x] remove SockJS
  - [x] improve logging, use `loglevel`
  - [x] don't mutate the options object (#1124)
  - [x] use internal-ip v3.0.0
  - [x] remove deprecated methods / support
- [x] **test**
- [x] #1055 
- [x] contribute sync methods to internal-ip ([default-gateway:6](https://github.com/silverwind/default-gateway/pull/6))

Please feel free to comment or make suggestions, but understand that this is purely for maintenance of the codebase as-is.

**Comment by shellscape** [comment]
🎉
